name: GitHub Pages

on:
  push:
    branches:
      - main  # Cambia "main" por la rama en la que deseas publicar tu sitio

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: www  # Cambia "www" por la carpeta que contiene tu sitio web